# Generated by Django 4.0.4 on 2023-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answer_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('choice', 'multiple choice')], max_length=15),
        ),
    ]
